import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { FiSearch } from "react-icons/fi"
import NavbarDropDown from '../components/Navbar Dropdown/NavbarDropdown'
import { useState, useRef, useEffect } from 'react'
import SearchDropdown from '../components/Search Dropdown/SearchDropdown'
import SingleAgent from '../common/Single Agent/SingleAgent'
import PaginationRounded from '../layout/Pagination'
import ArticleCard from '../common/Article Card/ArticleCard'
import Footer from '../common/Footer/Footer'


export default function Home() {

  const [showmenu, setShowMenu] = useState(false);
  const [showsearch, setShowSearch] = useState(false);
  const ref = useRef(null);

  useEffect(() => {
    function handleClickOutside(event) {
      if (ref.current && !ref.current.contains(event.target)) {
        setShowMenu(false)
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, [ref])




  return (
    <div className={styles.container}>
      <Head>
        <title>AgentBook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {/*==========       Homepage Section  =============*/}

      <div className={styles.homepage} ref={ref}>
        <div className={styles.navbar}>
          <Image src="/images/logo.png" width={190} height={48} objectFit="contain" />
          <div className={styles.nav_menu_box}>
            <div className={styles.flag_box}>
              <Image src="/images/flag.png" width={20} height={14} objectFit="contain" />
            </div>
            <div className={styles.nav_menu} onClick={() => setShowMenu(!showmenu)}>
              <Image src="/images/ham.png" width={21} height={12} objectFit="contain" />
              <Image src="/images/profile.png" width={30} height={23} objectFit="contain" />

              {showmenu && <NavbarDropDown />}

            </div>
          </div>
        </div>




        <div className={styles.homepage_box}>
          <div className={styles.homepage_text_box}>
            <h1 className={styles.homepage_text_heading}>Find The Perfect Real Estate Agent</h1>
            <span className={styles.homepage_text}>Make your search and sale easier and faster by connecting with one of our <br /> expert local agent in your neighborhood</span>
          </div>
          <div className={styles.homepage_searchbox}>
            <div className={styles.search_input_box}>
              <FiSearch className={styles.search_icon} onClick={() => { setShowSearch(!showsearch) }} />
              <input className={styles.search_input} type="text" />
              {showsearch && <SearchDropdown />}
            </div>
            <button className={styles.search_btn}>Search Agents</button>
          </div>
        </div>
      </div>




      {/*==========       Active Agent Section  =============*/}

      <div className={styles.active_agent_section}>
        <div className={styles.active_agent_box}>
          <h1 className={styles.active_agent_title}>Toronto’s Top Rated Agents</h1>
          <div className={styles.active_agent_heading}>Clients loved working with these agents</div>

          <div className={styles.agent_box}>
            <SingleAgent />


          </div>

          <div className={styles.pagination_box}>
            <PaginationRounded />
          </div>
        </div>

      </div>



      {/*==========       Choosing Agent Section  =============*/}

      <div className={styles.choose_agent_section}>
        <div className={styles.choose_agent_box}>
          <img src="../images/agenttree.png" alt="" />


          <div className={styles.choose_agent_content}>
            <div className={styles.choose_agent_content_box}>
              <div className={styles.choose_agent_title_box}>
                <span className={styles.choose_agent_heading}>CHOOSING YOUR AGENT</span>
                <h1 className={styles.choose_agent_title}>How to choose your agent</h1>
              </div>

              <div className={styles.choose_agent_box_desc}>
                <p className={styles.choose_agent_box_des_text}>You should choose an agent you are comfortable working with and <br /> who you feel has your best interests at heart. In order to make a <br /> decision, try asking prospective agents the following:</p>
                <div className={styles.choose_agent_box_list_section}>
                  <span className={styles.choose_agent_list_box}>
                    <div className={styles.choose_agent_list}></div>
                    <span className={styles.choose_agent_box_list}>How and where your property will be advertised</span>
                  </span>

                  <span className={styles.choose_agent_list_box}>
                    <div className={styles.choose_agent_list}></div>
                    <span className={styles.choose_agent_box_list}>Ask to see examples of their success in selling properties like yours</span>
                  </span>

                  <span className={styles.choose_agent_list_box}>
                    <div className={styles.choose_agent_list}></div>
                    <span className={styles.choose_agent_box_list}>How often you can expect feedback from the agent while your property is on the marke</span>
                  </span>
                </div>

                <div className={styles.choose_agent_box_btn_box}>
                  <button className={styles.choose_agent_box_btn}><FiSearch /> Find an Agent</button>
                </div>
              </div>

            </div>
          </div>
        </div>


      </div>



      {/*==========       Torontos Most Active Agents =============*/}

      <div className={styles.active_agent_section}>
        <div className={styles.active_agent_box}>
          <h1 className={styles.active_agent_title}>Toronto’s Most Active Agents</h1>
          <div className={styles.agent_box}>
            <SingleAgent />
          </div>

          <div className={styles.pagination_box}>
            <PaginationRounded />
          </div>
        </div>

      </div>


      {/*==========       Connect Box  =============*/}\
      <div className={styles.connect_box_section}>
        <div className={styles.connect_box}>
          <div className={styles.connect_box_text}>
            <h1 className={styles.connect_box_text_title}>Connect with an expert local agent </h1>
            <span className={styles.connect_box_text_heading}>Our agents are here to help you. Let’s make your home <br /> search or sale easier.</span>
          </div>

          <div className={styles.connect_box_search_box}>
            <input className={styles.connect_box_input} type="text" placeholder='Search by name or location' />
            <span className={styles.connect_box_icon_box}><FiSearch className={styles.connect_box_icon} /></span>
          </div>

        </div>
      </div>




      {/*==========       RealTime Conversation   =============*/}


      <div className={styles.choose_agent_section}>
        <div className={styles.realtime_agent_box}>
          <img src="../images/agent-left.jpg" alt="" />


          <div className={styles.choose_agent_content}>
            <div className={styles.choose_agent_content_box}>
              <div className={styles.choose_agent_title_box}>
                <span className={styles.choose_agent_heading}>CHAT WITH AN AGENT</span>
                <h1 className={styles.choose_agent_title}>Real Time Conversation</h1>
              </div>

              <div className={styles.choose_agent_box_desc}>
                <p className={styles.choose_agent_box_des_text}>You should choose an agent you are comfortable working with and <br /> who you feel has your best interests at heart. In order to make a <br /> decision, try asking prospective agents the following:</p>
                <div className={styles.choose_agent_box_list_section}>
                  <span className={styles.choose_agent_list_box}>
                    <div className={styles.choose_agent_list}></div>
                    <span className={styles.choose_agent_box_list}>How and where your property will be advertised</span>
                  </span>

                  <span className={styles.choose_agent_list_box}>
                    <div className={styles.choose_agent_list}></div>
                    <span className={styles.choose_agent_box_list}>Ask to see examples of their success in selling properties like yours</span>
                  </span>

                  <span className={styles.choose_agent_list_box}>
                    <div className={styles.choose_agent_list}></div>
                    <span className={styles.choose_agent_box_list}>How often you can expect feedback from the agent while your property is on the marke</span>
                  </span>
                </div>

                <div className={styles.choose_agent_box_btn_box}>
                  <button className={styles.choose_agent_box_btn}><FiSearch /> Find an Agent</button>
                </div>
              </div>

            </div>
          </div>
        </div>


      </div>


      {/*==========      Latest Articles By Agent   =============*/}

      <div className={styles.articlesby_section}>
        <div className={styles.articlesby_box}>
          <h1>Latest Articles By Agents</h1>

          <div className={styles.article_box}>
            <ArticleCard />
          </div>
          <div className={styles.pagination_box}>
            <PaginationRounded />
          </div>

        </div>
      </div>

      {/*==========      Footer   =============*/}
      
      <Footer/>


    </div >
  )
}
